---
title: "examine_LRAA_problems"
output: html_document
date: "2025-11-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}

ref_isoform_expression_data = read.csv("refDf.intron_ids_and_expression.tsv", header=T, sep="\t")

ref_isoform_expression_data %>% head()

```


```{r}

expr_results_data = read.csv("absRelativeDiffs.tsv", header=T, sep="\t")

expr_results_data %>% head()


```






```{r}

combined_data = left_join(ref_isoform_expression_data %>% rename(reference_tpm = tpm), 
                          expr_results_data,
                          by='intronId')


combined_data %>% head()


```


```{r}


isosceles_data = combined_data %>% filter(progname == "Isosceles")

LRAA_data = combined_data %>% filter(progname == "LRAA")


```


```{r}

isosceles_vs_LRAA = left_join(isosceles_data %>% select(transcript_ids, gene_ids, intronId, tpm, ref_tpm, relativeDiff) %>%
                                rename(isosceles_relDiff = relativeDiff, isosceles_tpm = tpm),
                            
                              LRAA_data %>% select(transcript_ids, tpm, relativeDiff) %>%
                                rename(LRAA_tpm = tpm, LRAA_relDiff = relativeDiff),
                              
                              by='transcript_ids' )



isosceles_vs_LRAA %>% head()

```


```{r}

library(viridis)

ggplot(isosceles_vs_LRAA, aes(x = isosceles_relDiff, y = LRAA_relDiff)) +
  geom_hex(bins=100) + 
  theme_bw() +
  # Use the viridis color palette for better visual representation of density
  scale_fill_viridis_c()
```


```{r}

isosceles_vs_LRAA %>% filter(isosceles_relDiff < 0.05 & ref_tpm > 1) %>% arrange(desc(LRAA_relDiff))



```

# focus on those where LRAA differs most from other top-performers.

```{r}

top_contenders_data = combined_data %>% filter(progname %in% c("LRAA", "Oarfish_align", "Isosceles", "Bambu"))

top_contenders_data %>% head()

```


```{r}

# get mean relativeDiff for non-LRAA for prioritization


```



```{r}

top_contenders_data %>% select(-intronId, -tpm) %>% spread(key=progname, value=relativeDiff) %>% head()


```




