---
title: "IGROV-1_quant-only-summary.Rmd"
output: html_document
date: "2025-07-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}

pearson_cor_df = read.csv("pearson_expr_cor.tsv", header=T, sep="\t")  %>% dplyr::select(name, cor_value)

pearson_cor_df$data_name = "IGROV-1"
```



```{r}
# rank according to mean cor val
pearson_cor_df_ranking = pearson_cor_df %>% group_by(name) %>% summarize(mcor = mean(cor_value)) %>% arrange(desc(mcor)) %>% pull(name)


pearson_cor_df$name = factor(pearson_cor_df$name, levels=pearson_cor_df_ranking)

```

```{r}

pearson_cor_df %>% ggplot(aes(x=name, y=cor_value)) + geom_col() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_wrap(~data_name, nrow=1) +
  ggtitle("IGROV-1 sim -  Pearson cor")


```


## Spearman Cor

```{r}

spearman_cor_df = read.csv("spearman_expr_cor.tsv", header=T, sep="\t")  %>% dplyr::select(name, cor_value)

spearman_cor_df$data_name = "IGROV-1"

spearman_cor_df %>% head()


```


```{r}
# rank according to mean cor val
spearman_cor_df_ranking = spearman_cor_df %>% group_by(name) %>% summarize(mcor = mean(cor_value)) %>% arrange(desc(mcor)) %>% pull(name)


spearman_cor_df$name = factor(spearman_cor_df$name, levels=pearson_cor_df_ranking)

```

```{r}

spearman_cor_df %>% ggplot(aes(x=name, y=cor_value)) + geom_col() +
   theme_bw() +
   theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
   facet_wrap(~data_name, nrow=1) +
  ggtitle("IGROV-1 sim - Spearman cor")


```

## Median relative difference

```{r}
median_rel_diff = read.csv("median_rel_diff.tsv", sep="\t", header=T) %>%
  dplyr::select(name, rel_diff)

median_rel_diff$data_name  = "IGROV-1"

median_rel_diff %>% head()
```


```{r}
# rank according to median relative difference
mrel_median_diff_ranking = median_rel_diff %>% group_by(name) %>% summarize(mrel_diff = mean(rel_diff)) %>% arrange(mrel_diff) %>% pull(name)


median_rel_diff$name = factor(median_rel_diff$name, levels=mrel_median_diff_ranking)

```


```{r}

median_rel_diff %>% ggplot(aes(x=name, y=rel_diff)) + geom_col() +
    theme_bw() +
   theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_wrap(~data_name, nrow=1) +
  ggtitle("Quant median relative difference for IGROV-1 simulated long isoform reads")


```

## Mean relative difference


```{r}
mean_rel_diff = read.csv("mean_rel_diff.tsv", sep="\t", header=T) %>%
  dplyr::select(name, rel_diff)

mean_rel_diff$data_name  = "IGROV-1"

mean_rel_diff %>% head()
```


```{r}
# rank according to median relative difference
mrel_mean_diff_ranking = mean_rel_diff %>% group_by(name) %>% summarize(mrel_diff = mean(rel_diff)) %>% arrange(mrel_diff) %>% pull(name)


mean_rel_diff$name = factor(mean_rel_diff$name, levels=mrel_mean_diff_ranking)

```


```{r}

mean_rel_diff %>% ggplot(aes(x=name, y=rel_diff)) + geom_col() +
  theme_bw() +
   theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_wrap(~data_name, nrow=1) +
   ggtitle("Quant mean relative difference for IGROV-1 simulated long isoform reads")


```





















